%% Calculate States of Interest
poi_3.COM = [0.04;0.845];%(m,m)
poi_2.COM = [-0.110;0.66];%(m,m)
poi_1.COM = [-0.301;0.635];%(m,m)
[~,~,poi_1.x] = find_points_near_function_output(...
    human_ts_pairs.next(1:6,:),COM_remap,poi_1.COM,0.02);
[~,~,poi_2.x] = find_points_near_function_output(...
    human_ts_pairs.next(1:6,:),COM_remap,poi_2.COM,0.02);
[~,~,poi_3.x] = find_points_near_function_output(...
    human_ts_pairs.next(1:6,:),COM_remap,poi_3.COM,0.02);

%% Local Analyses
model_dummy.A = model;
[poi_1.local_sys.taylor,poi_1.local_sys.simp] = ...
    calculate_local_systems_auto(model_dummy,SMP_lift,RBF_deriv_set,poi_1.x);
[poi_2.local_sys.taylor,poi_2.local_sys.simp] = ...
    calculate_local_systems_auto(model_dummy,SMP_lift,RBF_deriv_set,poi_2.x);
[poi_3.local_sys.taylor,poi_3.local_sys.simp] = ...
    calculate_local_systems_auto(model_dummy,SMP_lift,RBF_deriv_set,poi_3.x);

poi_1.local_sys.taylor.eig_info.COM_equil = ...
    COM_remap(poi_1.local_sys.taylor.eig_info.equil);
poi_2.local_sys.taylor.eig_info.COM_equil = ...
    COM_remap(poi_2.local_sys.taylor.eig_info.equil);
poi_3.local_sys.taylor.eig_info.COM_equil = ...
    COM_remap(poi_3.local_sys.taylor.eig_info.equil);

poi_1.local_sys.simp.eig_info.COM_equil = ...
    COM_remap(poi_1.local_sys.simp.eig_info.equil);
poi_2.local_sys.simp.eig_info.COM_equil = ...
    COM_remap(poi_2.local_sys.simp.eig_info.equil);
poi_3.local_sys.simp.eig_info.COM_equil = ...
    COM_remap(poi_3.local_sys.simp.eig_info.equil);

%% Save Information
save([folder,'/results_for_figures/paper_auto_results.mat'],...
    'clust','COM_remap','COM_remap_deriv',...
    'human_dataset','human_param',...
    'M','model','poi_1','poi_2','poi_3','RBF_centers','RBF_count',...
    'RBF_deriv_set','RBF_eval','RBF_set','SMP_lift',...
    'state_test_sim_history','z_test_sim_history');
