%% Define COM Remap Function
[COM_remap,COM_remap_deriv] = COM_remap_define(human_param);

%% Define Terminal Convergence Part of Trajectory
cutoff_threshold = 0.05;%m

human_dataset_terminal = human_dataset;
for subj_it = 1:human_dataset_terminal.subject_count
    subj = human_dataset_terminal.subjects{subj_it};
    for traj_it = 1:subj.traj_count
        traj = subj.traj{traj_it};
        tvec = traj.time;
        thvecs = traj.states(1:3,:);
        start_index = find_cutoff_from_threshold(COM_remap(thvecs),...
            cutoff_threshold);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.states_terminal = ...
            traj.states(:,start_index:end);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.time_terminal = ...
            traj.time(start_index:end);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.states_terminal_zeroed = ...
            human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.states_terminal - ...
            human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.states_terminal(:,end);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.time_terminal_zeroed = ...
            human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.time_terminal - ...
            human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.time_terminal(1);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.terminal_start = start_index;
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.t_count_terminal = length(...
            human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.time_terminal);
    end
end

%% Calculate Exponential Fits
init_params = [3.7,-18.94,42.29,-54.26,-0.1770,0.1492,0.1144];
param_lb = [0,-inf,-inf,-inf,-inf,-inf,-inf];
param_ub = [inf,inf,inf,inf,inf,inf,inf];
fit_options = optimoptions('lsqcurvefit',...
    'SpecifyObjectiveGradient',true,'Display','none');

for subj_it = 1:human_dataset_terminal.subject_count
    subj = human_dataset_terminal.subjects{subj_it};
    for traj_it = 1:subj.traj_count
        traj = subj.traj{traj_it};
        converge_fit = lsqcurvefit(@converge_fit_fun,init_params,...
            traj.time_terminal,traj.states_terminal(1:3,:),...
            param_lb,param_ub,fit_options);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.fit.params = converge_fit;
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.fit.eval = @(time) ...
            converge_fit_fun(converge_fit,time);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.fit.rate = converge_fit(1);
        human_dataset_terminal.subjects{subj_it}...
            .traj{traj_it}.fit.time_constant = 1/converge_fit(1);
    end
end

%% Save Analysis
save([folder,'/results_for_figures/paper_convergence_results.mat'],'COM_remap',...
    'COM_remap_deriv','human_dataset','human_param',...
    'cutoff_threshold','human_dataset_terminal');