function [F,J] = converge_fit_fun(param,tdata)

F = exp(-param(1).*tdata).*...
    [param(2);param(3);param(4)] + [param(5);param(6);param(7)];

if nargout > 1 % Jacobians
    J_1 = -exp(-param(1).*tdata).*tdata.*[param(2);param(3);param(4)];
    J_2 = exp(-param(1).*tdata).*[1;0;0];
    J_3 = exp(-param(1).*tdata).*[0;1;0];
    J_4 = exp(-param(1).*tdata).*[0;0;1];
    J_5 = ones(size(tdata)).*[1;0;0];
    J_6 = ones(size(tdata)).*[0;1;0];
    J_7 = ones(size(tdata)).*[0;0;1];

    J = [...
        reshape(J_1,[],1),...
        reshape(J_2,[],1),...
        reshape(J_3,[],1),...
        reshape(J_4,[],1),...
        reshape(J_5,[],1),...
        reshape(J_6,[],1),...
        reshape(J_7,[],1),...
        ];
end

end
